---
version: "2"

run:
  timeout: 1m

linters:
  default: none
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - errcheck
    - funlen
    - gochecknoinits
    - goconst
    - gocritic
    - gocyclo
    - revive
    - gosec
    - govet
    - ineffassign
    - misspell
    - nakedret
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
  settings:
    govet:
      enable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/sirupsen/logrus.FieldLogger).Infof
            - (github.com/sirupsen/logrus.FieldLogger).Warnf
            - (github.com/sirupsen/logrus.FieldLogger).Errorf
            - (github.com/sirupsen/logrus.FieldLogger).Fatalf
    gocyclo:
      min-complexity: 15
    goconst:
      min-len: 2
      min-occurrences: 2
    depguard:
      rules:
        default:
          deny:
            - pkg: "errors"
              desc: "Please use \"github.com/pkg/errors\" instead of \"errors\" in go imports"
    nakedret:
      max-func-lines: 30
    gocritic:
      enabled-checks:
        - appendCombine
        - boolExprSimplify
        - builtinShadow
        - commentedOutCode
        - commentedOutImport
        - docStub
        - dupImport
        - emptyFallthrough
        - emptyStringTest
        - equalFold
        - evalOrder
        - hexLiteral
        - hugeParam
        - importShadow
        - indexAlloc
        - initClause
        - methodExprCall
        - nestingReduce
        - nilValReturn
        - octalLiteral
        - paramTypeCombine
        - ptrToRefParam
        - rangeExprCopy
        - rangeValCopy
        - regexpPattern
        - sloppyReassign
        - stringXbytes
        - typeAssertChain
        - typeUnparen
        - unlabelStmt
        - unnamedResult
        - unnecessaryBlock
        - weakCond
        - yodaStyleExpr
  exclusions:
    rules:
      - path: "setup_test.go"
        linters:
          - funlen
      - path: "setup.go"
        linters:
          - gochecknoinits
          - gosec
      - path: "fanout_test.go"
        linters:
          - gosec
      - path: "setup_test.go"
        linters:
          - gocyclo
      - path: "client.go"
        linters:
          - gocritic

formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/networkservicemesh/sdk

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
